E4 07
IS-2022-equipos-2-4/ciencias-top pull request #12
Opened 2022-11-12 09:24 UTC by jorferg

Caso de uso: Buscar usuario.

2022-11-12 20:46 UTC, JoseEGJasso requested changes
Tu código no compila, te pongo en los demás comentarios por qué

2022-11-12 20:46 UTC, JoseEGJasso commented on src/main/java/com/unam/cienciastop/service/SvcUsuarioImpl.java
> +    private DaoProducto repoProducto;
Esta variable no la ocupas y no debería estar aquí

2022-11-12 20:46 UTC, JoseEGJasso commented on src/main/java/com/unam/cienciastop/dao/DaoUsuario.java
> +    public List<Usuario> getUsuarios_nombre(@Param("nombre") String nombre);
No importaste la anotación @Param

2022-11-13 02:32 UTC, jorferg commented on src/main/java/com/unam/cienciastop/service/SvcUsuarioImpl.java
> +    private DaoProducto repoProducto;
Ya elimine las varias de producto en el archivo correspondiente

2022-11-13 02:33 UTC, jorferg commented on src/main/java/com/unam/cienciastop/dao/DaoUsuario.java
> +    public List<Usuario> getUsuarios_nombre(@Param("nombre") String nombre);
Ya esta importada la etiqueta Param en el archivo correspondiente

2022-11-13 02:33 UTC, jorferg commented on src/main/java/com/unam/cienciastop/dao/DaoUsuario.java
> +    public List<Usuario> getUsuarios_nombre(@Param("nombre") String nombre);
Y una disculpa por no probar las cosas, era de madrugada y se me olvido como probar los cambios.

2022-11-13 19:29 UTC, JoseEGJasso requested changes
Tu codigo compila pero la aplicación no funciona. De nuevo, prueba tu código por favor, haz pruebas con postman y asegúrate de que esté funcionando

2022-11-13 19:29 UTC, JoseEGJasso commented on src/main/java/com/unam/cienciastop/service/SvcUsuarioImpl.java
> +    private SvcUsuario svcUsuario;
Esto no es necesario

2022-11-14 01:40 UTC, jorferg commented on src/main/java/com/unam/cienciastop/service/SvcUsuarioImpl.java
> +    private SvcUsuario svcUsuario;
Se removió la linea de código. Lamentablemente no puedo probar las cosas ahorita, mi distribución de linux esta fallando un poco y estoy tratando de arreglar el problema, no es grave, pero no me deja probar las cosas.

2022-11-14 04:11 UTC, JoseEGJasso requested changes

2022-11-14 04:11 UTC, JoseEGJasso commented on src/main/java/com/unam/cienciastop/dao/DaoUsuario.java
> +    @Query(value = "SELECT * FROM usuarios WHERE num_institucional = :num_institucional", nativeQuery = true)
Haz que las queries regresen una lista con todas las coincidencias

2022-11-14 04:11 UTC, JoseEGJasso commented on src/main/java/com/unam/cienciastop/dao/DaoUsuario.java
> +    @Query(value = "SELECT * FROM usuarios WHERE correo = :correo", nativeQuery = true)
Acá también

2022-11-14 05:06 UTC, jorferg commented on src/main/java/com/unam/cienciastop/dao/DaoUsuario.java
> +    @Query(value = "SELECT * FROM usuarios WHERE correo = :correo", nativeQuery = true)
Listo, ya regresan listas las dos observaciones. Espero no se me haya pasado nada esta vez.

2022-11-14 05:55 UTC, JoseEGJasso approved these changes

2022-11-14 05:58 UTC, merged