E2-13
IS-2022-equipos-2-4/ciencias-top pull request #21
Opened 2022-11-29 01:48 UTC by duranueva

Caso de uso finalizado (back). El caso de uso regresa la lista de objetos HistorialRentas. Cambios en Ctrl, Sev, SvcImp de Producto y DaoHistorialRentas

2022-11-29 04:11 UTC, SirMaik requested changes

2022-11-29 04:11 UTC, SirMaik commented on src/main/java/com/unam/cienciastop/controller/CtrlProducto.java
> +            @PathVariable(value = "id_usuario") Integer idEjemplar) {
Aquí has lo que hice yo con `@AuthenticationPrincipal` para sacar el número de cuenta del usuario que está haciendo la petición y con eso después puedes sacar el resto del usuario (igual como lo hice yo)

2022-11-30 18:57 UTC, duranueva commented on src/main/java/com/unam/cienciastop/controller/CtrlProducto.java
> +            @PathVariable(value = "id_usuario") Integer idEjemplar) {
Listisimo, probado y funcionando. Cambios en Ctrl, Svc, SvcImp de Producto. Ahora el metodo no necesita que se le pase id como parametro, sino que lo toma el numInstitucional del usuario que hace la peticion. Ya teniendo eso tomo el id y ahora hago la consulta. Grax mike

2022-12-01 04:11 UTC, SirMaik approved these changes

2022-12-04 01:54 UTC, merged