E2 05
IS-2022-equipos-2-4/ciencias-top pull request #9
Opened 2022-11-10 18:16 UTC by fcamachos

implementación de SumarPumapuntos

2022-11-11 05:50 UTC, SirMaik requested changes

2022-11-11 05:50 UTC, SirMaik commented on src/main/java/com/unam/cienciastop/controller/CtrlPumapuntos.java
> +        if(svc.Puma.getEsAdmin())
Quita el if y no hagas la verificación de privilegios de momento. Necesitamos primero que Itzel suba el inicio de sesión

2022-11-11 05:50 UTC, SirMaik commented on src/main/java/com/unam/cienciastop/controller/CtrlPumapuntos.java
> +        if(svc.Puma.getEsAdmin()){
Lo mismo que en el comentario anterior.

2022-11-11 05:50 UTC, SirMaik commented on src/main/java/com/unam/cienciastop/service/SvcPumapuntosImpl.java
> +        int saldo = repoPuma.findById(idUsuario).get().getSaldo();
Puedes mejor hacer:

```
PumaPuntos pumaPuntos = repoPuma.findById(idUsuario).get();
int saldo = pumaPuntos.getSaldo();
saldo += cantidad;
pumaPuntos.setSaldo(saldo);
repoPuma.save(pumaPuntos);
```

Pruébalo porfa :smiley:

2022-11-11 05:50 UTC, SirMaik commented on src/main/java/com/unam/cienciastop/dao/DaoPumapuntos.java
> +    void sumarPumapuntos(Integer idUsuario, Integer cantidad);
Nunca lo usas. Déjalo si quieres, quítalo o puedes usarlo en el servicio. Como prefieras.

2022-11-11 19:27 UTC, JoseEGJasso requested changes

2022-11-11 19:27 UTC, JoseEGJasso commented on src/main/java/com/unam/cienciastop/controller/CtrlPumapuntos.java
> +        // if(svc.Puma.getEsAdmin())
Elimina estos comentarios porfa para que no nos digan nada si revisan nuestro código. Lo mismo aplica con el resto de código comentado que dejaste dentro de los métodos

2022-11-11 19:27 UTC, JoseEGJasso commented on src/main/java/com/unam/cienciastop/controller/CtrlPumapuntos.java
> +    public ResponseEntity<Pumapuntos> sumarPumapuntos(
El tipo que regresaba esta función (`ResponseEntity<HttpStatus>`) estaba bien

2022-11-11 19:27 UTC, JoseEGJasso commented on src/main/java/com/unam/cienciastop/service/SvcPumapuntosImpl.java
> +    public PumaPuntos getPumapuntos(Integer idUsuario) {
Esta función debería regresar algo de tipo Integer

2022-11-11 19:27 UTC, JoseEGJasso commented on src/main/java/com/unam/cienciastop/service/SvcPumapuntos.java
> +    int getPumapuntos(Integer idUsuario);
Lo que regresa debería ser Integer en vez de int

2022-11-11 19:27 UTC, JoseEGJasso commented on src/main/java/com/unam/cienciastop/controller/CtrlPumapuntos.java
> +        // }
Aqui no llamaste a tu método de service

2022-11-11 19:27 UTC, JoseEGJasso commented on src/main/java/com/unam/cienciastop/service/SvcPumapuntosImpl.java
> +        PumaPuntos pumaPuntos = repoPuma.findById(idUsuario).get();
Prueba que esto funciona por favor

2022-11-11 19:32 UTC, JoseEGJasso requested changes

2022-11-11 19:32 UTC, JoseEGJasso commented on src/main/java/com/unam/cienciastop/service/SvcPumapuntosImpl.java
> +    public PumaPuntos getPumapuntos(Integer idUsuario) {
Esto también debería ser de tipo Integer

2022-11-14 05:47 UTC, JoseEGJasso requested changes
Modifica las anotaciones que te puse. Las definí erroneamente y no funciona como está ahorita

2022-11-14 05:47 UTC, JoseEGJasso commented on src/main/java/com/unam/cienciastop/controller/CtrlPumapuntos.java
> +        @PathVariable Integer idUsuario,
@PathVariable(value = "id_usuario") Integer idUsuario

2022-11-14 05:47 UTC, JoseEGJasso commented on src/main/java/com/unam/cienciastop/controller/CtrlPumapuntos.java
> +        @PathVariable Integer cantidad) {
@PathVariable(value = "cantidad") Integer cantidad

2022-11-14 05:47 UTC, JoseEGJasso commented on src/main/java/com/unam/cienciastop/controller/CtrlPumapuntos.java
> +    public ResponseEntity<Integer> getPumapuntos(@PathVariable Integer idUsuario) {
@PathVariable(value = "id_usuario") Integer idUsuario

2022-11-15 05:20 UTC, JoseEGJasso approved these changes

2022-11-15 05:21 UTC, JoseEGJasso approved these changes

2022-11-15 05:22 UTC, merged